ConfigParameterServer:
  ros__parameters: 
    /ti_mmwave/startFreq: "0"
    /ti_mmwave/idleTime: "0"
    /ti_mmwave/adcStartTime: "0"
    /ti_mmwave/rampEndTime: "0"
    /ti_mmwave/freqSlopeConst: "0"
    /ti_mmwave/numAdcSamples: "0"
    /ti_mmwave/digOutSampleRate: "0"
    /ti_mmwave/rxGain: "0"
    /ti_mmwave/chirpStartIdx: "0"
    /ti_mmwave/chirpEndIdx: "0"
    /ti_mmwave/numLoops: "0"
    /ti_mmwave/numFrames: "0"
    /ti_mmwave/framePeriodicity: "0"
    /ti_mmwave/zoneMinX: "0"
    /ti_mmwave/zoneMaxX: "0"
    /ti_mmwave/zoneMinY: "0"
    /ti_mmwave/zoneMaxY: "0"
    /ti_mmwave/zoneMinZ: "0"
    /ti_mmwave/zoneMaxZ: "0"
    /ti_mmwave/num_TX: "0"
    /ti_mmwave/f_s: "0"
    /ti_mmwave/f_c: "0"
    /ti_mmwave/BW: "0"
    /ti_mmwave/PRI: "0"
    /ti_mmwave/t_fr: "0"
    /ti_mmwave/max_range: "0"
    /ti_mmwave/range_resolution: "0"
    /ti_mmwave/max_doppler_vel: "0"
    /ti_mmwave/doppler_vel_resolution: "0"